{"timestamp":"2025-07-07T03:39:21.526317","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-07T03:39:21.528831","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/new_conn.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-07T03:39:21.827218Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-07T03:39:21.828663Z","level":"info","event":" Previous state of the Task instance: queued","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-07T03:39:21.830619Z","level":"info","event":"Current task name:load_csv","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-07T03:39:21.837829Z","level":"info","event":"Dag name:new_conn","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-07T03:39:21.930753","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"connection to server at \"localhost\" (::1), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\nconnection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":825,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1088,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/new_conn.py","lineno":9,"name":"load_csv_to_postgres"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}]}]}
{"timestamp":"2025-07-07T03:39:21.935793Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-07T03:39:21.937088Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-07T03:39:21.938741Z","level":"info","event":"Task:<Task(PythonOperator): load_csv>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-07T03:39:21.940175Z","level":"info","event":"Failure caused by connection to server at \"localhost\" (::1), port 5432 failed: Connection refused","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-07T03:39:21.941327Z","level":"info","event":"\tIs the server running on that host and accepting TCP/IP connections?","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-07T03:39:21.942123Z","level":"info","event":"connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-07T03:39:21.951189Z","level":"info","event":"\tIs the server running on that host and accepting TCP/IP connections?","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-07T03:39:21.954037Z","level":"info","event":"","chan":"stdout","logger":"task"}
